package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Denunciasofertas generated by hbm2java
 */
public class Denunciasofertas  implements java.io.Serializable {


     private DenunciasofertasId id;

    public Denunciasofertas() {
    }

    public Denunciasofertas(DenunciasofertasId id) {
       this.id = id;
    }
   
    public DenunciasofertasId getId() {
        return this.id;
    }
    
    public void setId(DenunciasofertasId id) {
        this.id = id;
    }




}


