package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Denunciasrecetas generated by hbm2java
 */
public class Denunciasrecetas  implements java.io.Serializable {


     private DenunciasrecetasId id;

    public Denunciasrecetas() {
    }

    public Denunciasrecetas(DenunciasrecetasId id) {
       this.id = id;
    }
   
    public DenunciasrecetasId getId() {
        return this.id;
    }
    
    public void setId(DenunciasrecetasId id) {
        this.id = id;
    }




}


