package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * EstarId generated by hbm2java
 */
public class EstarId  implements java.io.Serializable {


     private int idSupermercado;
     private int idOferta;

    public EstarId() {
    }

    public EstarId(int idSupermercado, int idOferta) {
       this.idSupermercado = idSupermercado;
       this.idOferta = idOferta;
    }
   
    public int getIdSupermercado() {
        return this.idSupermercado;
    }
    
    public void setIdSupermercado(int idSupermercado) {
        this.idSupermercado = idSupermercado;
    }
    public int getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(int idOferta) {
        this.idOferta = idOferta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstarId) ) return false;
		 EstarId castOther = ( EstarId ) other; 
         
		 return (this.getIdSupermercado()==castOther.getIdSupermercado())
 && (this.getIdOferta()==castOther.getIdOferta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSupermercado();
         result = 37 * result + this.getIdOferta();
         return result;
   }   


}


