package entity;
// Generated 24-abr-2022 19:21:23 by Hibernate Tools 4.3.1

/**
 * Estar generated by hbm2java
 */
public class Estar implements java.io.Serializable {

    private Integer id;
    private Integer idSupermercado;
    private Integer idOferta;

    public Estar() {
    }

    public Estar(Integer idSupermercado, Integer idOferta) {
        this.idSupermercado = idSupermercado;
        this.idOferta = idOferta;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIdSupermercado() {
        return this.idSupermercado;
    }

    public void setIdSupermercado(Integer idSupermercado) {
        this.idSupermercado = idSupermercado;
    }

    public Integer getIdOferta() {
        return this.idOferta;
    }

    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }

}
