package entity;
// Generated 30-abr-2022 18:28:06 by Hibernate Tools 4.3.1



/**
 * Estar generated by hbm2java
 */
public class Estar  implements java.io.Serializable {


     private EstarId id;

    public Estar() {
    }

    public Estar(EstarId id) {
       this.id = id;
    }
   
    public EstarId getId() {
        return this.id;
    }
    
    public void setId(EstarId id) {
        this.id = id;
    }




}


