package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * FavoritosrecetasId generated by hbm2java
 */
public class FavoritosrecetasId  implements java.io.Serializable {


     private int idUsuario;
     private int idReceta;

    public FavoritosrecetasId() {
    }

    public FavoritosrecetasId(int idUsuario, int idReceta) {
       this.idUsuario = idUsuario;
       this.idReceta = idReceta;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavoritosrecetasId) ) return false;
		 FavoritosrecetasId castOther = ( FavoritosrecetasId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdReceta()==castOther.getIdReceta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdReceta();
         return result;
   }   


}


