package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Favoritosrecetas generated by hbm2java
 */
public class Favoritosrecetas  implements java.io.Serializable {


     private FavoritosrecetasId id;

    public Favoritosrecetas() {
    }

    public Favoritosrecetas(FavoritosrecetasId id) {
       this.id = id;
    }
   
    public FavoritosrecetasId getId() {
        return this.id;
    }
    
    public void setId(FavoritosrecetasId id) {
        this.id = id;
    }




}


