package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer id;
     private Float precio;
     private String precioUnidad;
     private String imagen;
     private Integer idUsuario;

    public Oferta() {
    }

    public Oferta(Float precio, String precioUnidad, String imagen, Integer idUsuario) {
       this.precio = precio;
       this.precioUnidad = precioUnidad;
       this.imagen = imagen;
       this.idUsuario = idUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(String precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


