package entity;
// Generated 30-abr-2022 18:28:06 by Hibernate Tools 4.3.1



/**
 * Publicar generated by hbm2java
 */
public class Publicar  implements java.io.Serializable {


     private PublicarId id;

    public Publicar() {
    }

    public Publicar(PublicarId id) {
       this.id = id;
    }
   
    public PublicarId getId() {
        return this.id;
    }
    
    public void setId(PublicarId id) {
        this.id = id;
    }




}


