package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Receta generated by hbm2java
 */
public class Receta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String tiempo;
     private Integer comensales;
     private String pasos;
     private String utensilios;
     private Integer likes;
     private String imagen;
     private Integer idUsuario;

    public Receta() {
    }

    public Receta(String nombre, String tiempo, Integer comensales, String pasos, String utensilios, Integer likes, String imagen, Integer idUsuario) {
       this.nombre = nombre;
       this.tiempo = tiempo;
       this.comensales = comensales;
       this.pasos = pasos;
       this.utensilios = utensilios;
       this.likes = likes;
       this.imagen = imagen;
       this.idUsuario = idUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    public Integer getComensales() {
        return this.comensales;
    }
    
    public void setComensales(Integer comensales) {
        this.comensales = comensales;
    }
    public String getPasos() {
        return this.pasos;
    }
    
    public void setPasos(String pasos) {
        this.pasos = pasos;
    }
    public String getUtensilios() {
        return this.utensilios;
    }
    
    public void setUtensilios(String utensilios) {
        this.utensilios = utensilios;
    }
    public Integer getLikes() {
        return this.likes;
    }
    
    public void setLikes(Integer likes) {
        this.likes = likes;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


