package entity;
// Generated 28-may-2022 19:18:53 by Hibernate Tools 4.3.1



/**
 * RelacionetiquetaId generated by hbm2java
 */
public class RelacionetiquetaId  implements java.io.Serializable {


     private int idEtq1;
     private int idEtq2;

    public RelacionetiquetaId() {
    }

    public RelacionetiquetaId(int idEtq1, int idEtq2) {
       this.idEtq1 = idEtq1;
       this.idEtq2 = idEtq2;
    }
   
    public int getIdEtq1() {
        return this.idEtq1;
    }
    
    public void setIdEtq1(int idEtq1) {
        this.idEtq1 = idEtq1;
    }
    public int getIdEtq2() {
        return this.idEtq2;
    }
    
    public void setIdEtq2(int idEtq2) {
        this.idEtq2 = idEtq2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelacionetiquetaId) ) return false;
		 RelacionetiquetaId castOther = ( RelacionetiquetaId ) other; 
         
		 return (this.getIdEtq1()==castOther.getIdEtq1())
 && (this.getIdEtq2()==castOther.getIdEtq2());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEtq1();
         result = 37 * result + this.getIdEtq2();
         return result;
   }   


}


