package entity;
// Generated 30-abr-2022 18:28:06 by Hibernate Tools 4.3.1



/**
 * Supermercado generated by hbm2java
 */
public class Supermercado  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Float longitud;
     private Float latitud;
     private String direccion;

    public Supermercado() {
    }

    public Supermercado(String nombre, Float longitud, Float latitud, String direccion) {
       this.nombre = nombre;
       this.longitud = longitud;
       this.latitud = latitud;
       this.direccion = direccion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }
    public Float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


