package entity;
// Generated 24-abr-2022 19:21:23 by Hibernate Tools 4.3.1

/**
 * Tener generated by hbm2java
 */
public class Tener implements java.io.Serializable {

    private Integer id;
    private Integer idEtiqueta;
    private Integer idOferta;
    private Boolean especial;

    public Tener() {
    }

    public Tener(Integer idEtiqueta, Integer idOferta, Boolean especial) {
        this.idEtiqueta = idEtiqueta;
        this.idOferta = idOferta;
        this.especial = especial;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIdEtiqueta() {
        return this.idEtiqueta;
    }

    public void setIdEtiqueta(Integer idEtiqueta) {
        this.idEtiqueta = idEtiqueta;
    }

    public Integer getIdOferta() {
        return this.idOferta;
    }

    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }

    public Boolean getEspecial() {
        return this.especial;
    }

    public void setEspecial(Boolean especial) {
        this.especial = especial;
    }

}
