package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * Tenerproducto generated by hbm2java
 */
public class Tenerproducto  implements java.io.Serializable {


     private TenerproductoId id;
     private Double cantidad;
     private String unidadmedida;

    public Tenerproducto() {
    }

	
    public Tenerproducto(TenerproductoId id) {
        this.id = id;
    }
    public Tenerproducto(TenerproductoId id, Double cantidad, String unidadmedida) {
       this.id = id;
       this.cantidad = cantidad;
       this.unidadmedida = unidadmedida;
    }
   
    public TenerproductoId getId() {
        return this.id;
    }
    
    public void setId(TenerproductoId id) {
        this.id = id;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public String getUnidadmedida() {
        return this.unidadmedida;
    }
    
    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }




}


