package entity;
// Generated 30-may-2022 12:51:53 by Hibernate Tools 4.3.1



/**
 * TenerproductoId generated by hbm2java
 */
public class TenerproductoId  implements java.io.Serializable {


     private int idProducto;
     private int idReceta;

    public TenerproductoId() {
    }

    public TenerproductoId(int idProducto, int idReceta) {
       this.idProducto = idProducto;
       this.idReceta = idReceta;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TenerproductoId) ) return false;
		 TenerproductoId castOther = ( TenerproductoId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdReceta()==castOther.getIdReceta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProducto();
         result = 37 * result + this.getIdReceta();
         return result;
   }   


}


