package entity;
// Generated 30-abr-2022 18:28:06 by Hibernate Tools 4.3.1



/**
 * TenerId generated by hbm2java
 */
public class TenerId  implements java.io.Serializable {


     private int idEtiqueta;
     private int idOferta;

    public TenerId() {
    }

    public TenerId(int idEtiqueta, int idOferta) {
       this.idEtiqueta = idEtiqueta;
       this.idOferta = idOferta;
    }
   
    public int getIdEtiqueta() {
        return this.idEtiqueta;
    }
    
    public void setIdEtiqueta(int idEtiqueta) {
        this.idEtiqueta = idEtiqueta;
    }
    public int getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(int idOferta) {
        this.idOferta = idOferta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TenerId) ) return false;
		 TenerId castOther = ( TenerId ) other; 
         
		 return (this.getIdEtiqueta()==castOther.getIdEtiqueta())
 && (this.getIdOferta()==castOther.getIdOferta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEtiqueta();
         result = 37 * result + this.getIdOferta();
         return result;
   }   


}


